### ISSUE TITLE
COFFEE-011 Home Button

### ISSUE THREAD

**Issue by bengaal** [sw21-tug/Team_01#11]
COFFEE-011

User Story:
**As a** user

**I want** to have a menu I can navigate

**so that** I can switch between the different views (Home, Add Coffee, Search, Support).

Development task:
In the menu clicking the Home Button navigates the user to a The Home Screen.

# Estimated Effort
2

# Functional Criteria
- [ ] Navigates back to Home

# Technical Criteria
- [ ] Navigation is successful

# Acceptance criteria
- [ ] The Button Navigates us to the Home screen

# Hints / Useful Links
- https://google.com

**Comment by xqndi** [comment]
Home Button-Functionality was already working through used template. Removed unwanted template-relics. (Unwanted navigation screens, unwanted icons)
