### ISSUE TITLE
COFFEE-012 Scrollable Home

### ISSUE THREAD

**Issue by bengaal** [sw21-tug/Team_01#13]
COFFEE-012

User Story:
**As a** user

**I want** to be able to scroll on the home screen to discover more coffees

**so that** I can see more coffees on the home screen

Development task:
The home screen is scrollable, and has 10 items to display. 3 images fill the screen. 

# Estimated Effort
5

# Functional Criteria
- [ ] Screen is scrollable
- [ ] Screen has 3 items visible at once
- [ ] Altogether there are 10 items

# Technical Criteria
- [ ] Screen is scrollable
- [ ] Tile sizes are appropriate
- [ ] Images look good

# Acceptance criteria
- [ ] See other criteria

# Hints / Useful Links
- https://developer.android.com/reference/kotlin/android/widget/ScrollView

**Comment by goschale** [comment]
Doing this Issue together with the second issue. because it is less work to already implement the list view and just design one row for the view
