### ISSUE TITLE
COFFEE-003 Menu Button

### ISSUE THREAD

**Issue by bengaal** [sw21-tug/Team_01#3]
COFFEE-003

**As a** user

**I want** to have a menu button on the home screen

**so that** I can click on it.

# Estimated Workload
2

# Functional Criteria
- [ ] The button is clickable
- [ ] The button is positioned in the upper left corner

# Technical Criteria
- [ ] It's a button
- [ ] It's a hamburger button

# Acceptance criteria
- [ ] A hamburger button is displayed in the upper left corner.

# Hints / Useful Links

**Comment by xqndi** [comment]
Issue was already finished with start-template-design
